# Supabase CLI configuration
# Fill YOUR_PROJECT_REF from Supabase Dashboard → Settings → General → Project Reference

project_id = "nqmfytuxboiwdumnovlz"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000
port = 54321
external_url = "http://127.0.0.1:54321"

[db]
port = 54322
shadow_port = 54320
major_version = 17
root_key = ""

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true
# For local dev; does not impact hosted project
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
jwt_secret = "YOUR_LOCAL_JWT_SECRET"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 3600


