[build]
  # Base directory for builds (where the Next.js app is located)
  base = "frontend"

  # Build command to run
  command = "npm run build"

  # Directory to publish (Next.js build output)
  publish = ".next"

[build.environment]
  # Node.js version (required for Next.js 15.5.3)
  NODE_VERSION = "18"

  # Next.js specific environment variables
  NEXT_TELEMETRY_DISABLED = "1"

  # Build optimization
  NPM_FLAGS = "--legacy-peer-deps"

# Next.js Runtime Plugin for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Static file caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API route configuration
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
  autoLaunch = false

# =====================================
# ENVIRONMENT VARIABLES CONFIGURATION
# =====================================
# Add these in Netlify Dashboard > Site Settings > Environment Variables:
#
# Required for Database:
# DATABASE_URL = "postgresql://neondb_owner:npg_N8SU2rbhfViZ@ep-solitary-dawn-aedihqsd-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
#
# Required for AI Analysis:
# GEMINI_API_KEY = "your_google_gemini_api_key"
# GOOGLE_GEMINI_API_KEY = "your_google_gemini_api_key"
#
# Required for Authentication (Supabase):
# NEXT_PUBLIC_SUPABASE_URL = "https://fbjjqwfcmzrpmytieajp.supabase.co"
# NEXT_PUBLIC_SUPABASE_ANON_KEY = "your_supabase_anon_key"
# SUPABASE_URL = "https://fbjjqwfcmzrpmytieajp.supabase.co"
# SUPABASE_ANON_KEY = "your_supabase_anon_key"
#
# Optional Performance Settings:
# RATE_LIMIT_REQUESTS_PER_MINUTE = "30"
# RATE_LIMIT_WINDOW_MS = "60000"
# CACHE_TTL_SECONDS = "3600"