[build]
  # Base directory for builds (where the Next.js app is located)
  base = "frontend"

  # Build command to run
  command = "npm run build"

  # Directory to publish (Next.js build output)
  publish = ".next"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

  # Next.js specific environment variables
  NEXT_TELEMETRY_DISABLED = "1"

# Next.js Runtime Plugin for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Static file caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API route configuration
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
  autoLaunch = false